template: true
valuesFilePath: ./values.yml

resources:
 - name: gorepo
   type: GitRepo
   configuration:
    gitProvider: {{ .Values.gorepo.gitProvider }}
    path: {{ .Values.gorepo.path }}
    branches:
     include: master
 - name: go_docker_image
   type: Image
   configuration:
    registry: test_docker_build
    sourceRepository: jfrogdockerbuild
    imageName: punchhdev.jfrog.io/jfrogdockerbuild/goimage
    imageTag: latest

pipelines:
 - name: build_pipeline
   configuration:
    runtime:
     type: image
     image:
       auto:
        language: go
        versions:
         - 1.12
   steps:
    - name: docker_build
      type: Bash
      configuration:
       integrations:
        - name: test_docker_build
       inputResources:
        - name: gorepo
       outputResources:
        - name: go_docker_image
      execution:
       onStart:
        - echo "hello"
