template: true
valuesFilePath: ./values.yml

resources:
 - name: gorepo
   type: GitRepo
   configuration:
    gitProvider: {{ .Values.gorepo.gitProvider }}
    path: {{ .Values.gorepo.path }}
    branches:
     include: master
 - name: go_docker_image
   type: Image
   configuration:
    registry: test_docker_build
    sourceRepository: jfrogdockerbuild
    imageName: punchhdev.jfrog.io/jfrogdockerbuild/goimage
    imageTag: latest

pipelines:
 - name: build_pipeline
   configuration:
    runtime:
     type: image
     image:
       auto:
        language: go
        versions:
         - 1.12
   steps:
    - name: docker_build
      type: Bash
      configuration:
       integrations:
        - name: test_docker_build
       inputResources:
        - name: gorepo
       outputResources:
        - name: go_docker_image
      execution:
       onStart:
        - pwd
       onExecute:
        - |
           if [[ $res_gorepo_branchName -eq "master"]];
           then 
            pushd $res_gorepo_resourcePath
            retry_command jfrog rt config --url $int_test_docker_build_url --user $int_test_docker_build_user --apikey $int_test_docker_build_apikey
            docker build -t $res_go_docker_image_imageName:latest -f Dockerfile.yml .
            jfrog rt docker-push $res_go_docker_image_imageName:latest $res_go_docker_image_sourceRepository
           fi 
       onSuccess:
        - |
           if [[ $res_gorepo_branchName -eq "master"] && [ $res_gorepo_isPullRequest -eq false]];
           then
            #  shipctl put_resource_state_multi docker_image_event_webhook_service "versionName=$COMMIT sourceName=$DOCKER_ACC/$DOCKER_REPO buildNumber=$BUILD_NUMBER"
           fi
